# Generated by Django 3.2.16 on 2022-12-04 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insertion_date', models.DateTimeField(auto_now_add=True, verbose_name='Insertion Date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Example: What country is inside South Africa?', max_length=100, verbose_name='Question')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproj.quizcollection')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Insertion Date')),
                ('answer', models.CharField(blank=True, help_text='Example: Lesotho', max_length=100, null=True, verbose_name='Question')),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answer', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproj.quizquestion')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
