# Generated by Django 3.2.16 on 2022-12-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='answer',
            field=models.CharField(blank=True, help_text='Fill with your answer', max_length=100, null=True, verbose_name='Answer'),
        ),
    ]
